# 1. Create a 3x3x3 array with random values 

In [4]:
import numpy as np
arr = np.random.random((3,3,3))
arr

array([[[0.28659523, 0.28764957, 0.43895188],
        [0.60612669, 0.29491788, 0.37015677],
        [0.61877764, 0.44025027, 0.75408509]],

       [[0.29065112, 0.85028706, 0.08094387],
        [0.50456067, 0.15744676, 0.33944682],
        [0.53421152, 0.33003964, 0.7685461 ]],

       [[0.02656272, 0.02051215, 0.38142363],
        [0.38043047, 0.81570824, 0.55937446],
        [0.35777327, 0.04752837, 0.7183529 ]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
arr = np.diag([1,2,3,4],-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [11]:
arr = np.zeros((8,8),dtype=int)
arr[::2,1::2]=1
arr[1::2,::2]=1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [16]:
arr= np.random.random((5,5))
print("Original Array:")
print(arr)
arrmax, arrmin = arr.max(), arr.min()
norm_arr = (arr - arrmin)/(arrmax - arrmin)
print("After normalization:")
print(norm_arr)

Original Array:
[[0.85573674 0.17513893 0.97886271 0.05472597 0.95809949]
 [0.41210525 0.01094809 0.46521045 0.57031721 0.09362777]
 [0.74676454 0.56658913 0.4182706  0.73018387 0.18368351]
 [0.19889773 0.74100919 0.24689897 0.00490891 0.97531425]
 [0.98659929 0.83822258 0.33800592 0.03475129 0.60861974]]
After normalization:
[[0.86669672 0.17340499 0.99211913 0.0507462  0.97096865]
 [0.41479101 0.00615181 0.46888668 0.5759538  0.09037356]
 [0.75569207 0.57215618 0.42107135 0.73880215 0.18210894]
 [0.19760693 0.74982937 0.24650344 0.         0.98850449]
 [1.         0.8488559  0.33930964 0.03039897 0.61497071]]


# 5.  How to find common values between two arrays?

In [8]:
arr1=[4,6,2,3,8]
print("Array 1 : ", arr1)
arr2=[1,5,4,7,6,8]
print("Array 2 : ", arr2)
print("Common Values between two arrays : ", np.intersect1d(arr1,arr2))

Array 1 :  [4, 6, 2, 3, 8]
Array 2 :  [1, 5, 4, 7, 6, 8]
Common Values between two arrays :  [4 6 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [17]:
today = np.datetime64('today')
yesterday=np.datetime64(today)-np.timedelta64(1)
print("Yesterday : ",yesterday)
print("Today : ",today)
tommorow = np.datetime64(today)+np.timedelta64(1)
print("Tommorow : ",tommorow)

Yesterday :  2020-07-27
Today :  2020-07-28
Tommorow :  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [30]:
arrA=np.random.randint(0,5,5)
print("Array 1 : ", arrA)
arrB=np.random.randint(0,5,5)
print("Array 2 : ", arrB)
result = np.array_equal(arrA,arrB)
result

Array 1 :  [1 4 4 4 0]
Array 2 :  [4 0 3 0 0]


False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [33]:
arr=np.random.random(10)
print(arr)
arr[arr.argmax()]=0
print(arr)

[0.48129457 0.04829548 0.87301498 0.32136144 0.75962074 0.08310969
 0.32058145 0.15048974 0.08944835 0.12486178]
[0.48129457 0.04829548 0.         0.32136144 0.75962074 0.08310969
 0.32058145 0.15048974 0.08944835 0.12486178]


# 9. How to print all the values of an array?

In [37]:
arr=np.empty((10),dtype=int)
print(arr)

[6488161 7209071 6357092 6029363 6488147 6881394 7602288 3866739 3801155
 5570652]


# 10.Subtract the mean of each row of a matrix

In [38]:
arr = np.random.rand(2, 4)
print("Original matrix:\n",arr)
res_arr = arr - arr.mean(axis=1, keepdims=True)
print("\nSubtract the mean of each row of the original matrix:\n",res_arr)

Original matrix:
 [[0.86372839 0.86896847 0.33488775 0.58071708]
 [0.36861848 0.74868672 0.86066636 0.31252189]]

Subtract the mean of each row of the original matrix:
 [[ 0.20165297  0.20689305 -0.32718767 -0.08135834]
 [-0.20400488  0.17606336  0.288043   -0.26010147]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [5]:
import numpy as np
arr = np.random.randint(0, 10, 5)
print(arr)
arr1 = [1,2,3]
arr[arr1] +=1
print(arr)

[5 7 0 4 5]
[5 8 1 5 5]


# 12.How to get the diagonal of a dot product?

In [40]:
first_arr = np.random.randint(0,10,(3,3))
print("First Array : \n",first_arr)
second_arr= np.random.randint(0,10,(3,3))
print("Second Array : \n",second_arr)
dot_product = np.dot(first_arr, second_arr)
Diag_result=np.diag(dot_product)
print("diagonal of a dot product : \n",Diag_result)

First Array : 
 [[8 7 1]
 [1 0 7]
 [3 8 0]]
Second Array : 
 [[2 3 4]
 [1 1 0]
 [4 6 8]]
diagonal of a dot product : 
 [27 45 12]


# 13.How to find the most frequent value in an array?

In [42]:
arr = np.random.randint(0, 10, 40)
print("Original array:\n",arr)
res = np.bincount(arr).argmax()
print("Most frequent value in the above array : ",res)

Original array:
 [8 0 8 6 4 8 9 1 6 2 0 1 1 7 6 1 1 5 7 4 0 0 1 1 7 9 1 5 6 3 7 5 3 8 5 3 5
 7 2 8]
Most frequent value in the above array :  1


# 14.How to get the n largest values of an array

In [47]:
arr = np.arange(10)
np.random.shuffle(arr)
print("Original array:",arr)
n = 3
res = arr[np.argsort(arr)[-n:]]
print("Largest n values of an array : ",res)

Original array: [8 3 6 5 7 1 0 4 2 9]
Largest n values of an array :  [7 8 9]


# 15.How to create a record array from a regular array?

In [51]:
arr1=np.array([8,3,6,2])
arr2=np.array(['Black','Blue','White','Red'])
arr3=np.array([10,20,30,40])
result= np.core.records.fromarrays([arr1, arr2, arr3],names='a,b,c')
result

rec.array([(8, 'Black', 10), (3, 'Blue', 20), (6, 'White', 30),
           (2, 'Red', 40)],
          dtype=[('a', '<i4'), ('b', '<U5'), ('c', '<i4')])